#!/bin/bash
mkdir -p attendance_tracker_v1
touch attendance_tracker_v1/attendance_checker.py
mkdir -p attendance_tracker_v1/Helpers
touch attendance_tracker_v1/Helpers/assets.csv
touch attendance_tracker_v1/Helpers/config.json
mkdir -p attendance_tracker_v1/reports
touch attendance_tracker_v1/reports/reports.log

echo "Files and directories have been created successfully"
